version: '3.9'

services:
  myscaledb1:
    container_name: myscaledb1
    hostname: myscaledb1
    image: myscale/myscaledb:${MYSCALEDB_IMAGE_VERSION}
    # tty: true
    expose:
      # MyScaleDB 端口
      - '8123'
      - '9000'
      - '8998'
      - '9363'
      - '9116'
    ports:
      - '${MYSCALEDB_1_HTTP_PORT}:8123'
      - '${MYSCALEDB_1_INTER_SERVER_PORT}:9000'
    networks:
      - myscaledb_network
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb1/data:/var/lib/clickhouse
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb1/log:/var/log/clickhouse-server
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/custom_users_config.xml:/etc/clickhouse-server/users.d/custom_users_config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/distributed-ddl.xml:/etc/clickhouse-server/config.d/distributed-ddl.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/2share2replica_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/myscaledb_1_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 4Gb

  myscaledb2:
    container_name: myscaledb2
    hostname: myscaledb2
    image: myscale/myscaledb:${MYSCALEDB_IMAGE_VERSION}
    # tty: true
    expose:
      # MyScaleDB 端口
      - '8123'
      - '9000'
      - '8998'
      - '9363'
      - '9116'
    ports:
      - '${MYSCALEDB_2_HTTP_PORT}:8123'
      - '${MYSCALEDB_2_INTER_SERVER_PORT}:9000'
    networks:
      - myscaledb_network
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb2/data:/var/lib/clickhouse
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb2/log:/var/log/clickhouse-server
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/custom_users_config.xml:/etc/clickhouse-server/users.d/custom_users_config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/distributed-ddl.xml:/etc/clickhouse-server/config.d/distributed-ddl.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/2share2replica_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/myscaledb_2_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 4Gb

  myscaledb3:
    container_name: myscaledb3
    hostname: myscaledb3
    image: myscale/myscaledb:${MYSCALEDB_IMAGE_VERSION}
    # tty: true
    expose:
      # MyScaleDB 端口
      - '8123'
      - '9000'
      - '8998'
      - '9363'
      - '9116'
    ports:
      - '${MYSCALEDB_3_HTTP_PORT}:8123'
      - '${MYSCALEDB_3_INTER_SERVER_PORT}:9000'
    networks:
      - myscaledb_network
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb3/data:/var/lib/clickhouse
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb3/log:/var/log/clickhouse-server
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/custom_users_config.xml:/etc/clickhouse-server/users.d/custom_users_config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/distributed-ddl.xml:/etc/clickhouse-server/config.d/distributed-ddl.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/2share2replica_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/myscaledb_3_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 4Gb

  myscaledb4:
    container_name: myscaledb4
    hostname: myscaledb4
    image: myscale/myscaledb:${MYSCALEDB_IMAGE_VERSION}
    # tty: true
    expose:
      # MyScaleDB 端口
      - '8123'
      - '9000'
      - '8998'
      - '9363'
      - '9116'
    ports:
      - '${MYSCALEDB_4_HTTP_PORT}:8123'
      - '${MYSCALEDB_4_INTER_SERVER_PORT}:9000'
    networks:
      - myscaledb_network
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb4/data:/var/lib/clickhouse
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/myscaledb4/log:/var/log/clickhouse-server
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/custom_users_config.xml:/etc/clickhouse-server/users.d/custom_users_config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/distributed-ddl.xml:/etc/clickhouse-server/config.d/distributed-ddl.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/2share2replica_config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${DOCKER_VOLUME_DIRECTORY:-.}/configs/myscaledb_4_macros.xml:/etc/clickhouse-server/config.d/macros.xml
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 4Gb
